#!/usr/bin/env python
"""Generate the ETC field reference (Markdown tables) from the JSON schemas (plan S20).

Usage:
    python scripts/gen_field_reference.py [--out docs/_generated/field_reference_tables.md]

``docs/conf.py`` calls :func:`write` at every documentation build, so the "ETC field reference"
page (``docs/field_reference.md``, which includes the generated file) cannot drift from
``keck_etcs/schema/etc_input.json`` and ``etc_output.json``. One row per leaf field (dotted path, as in
``docs/wmko_api_note.md``): type, range or allowed values, default, unit (``x-unit``) and description.
``scripts/check_docs.py`` checks that the tables list every leaf field of both schemas.

Standard library only; the schemas are read from the repository, not from the installed package.
"""
import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCHEMA_DIR = REPO / 'keck_etcs' / 'schema'
DEFAULT_OUT = REPO / 'docs' / '_generated' / 'field_reference_tables.md'


def _resolve(prop, root):
    ref = prop.get('$ref')
    if ref and ref.startswith('#/$defs/'):
        return {**root['$defs'][ref.split('/')[-1]], **{k: v for k, v in prop.items() if k != '$ref'}}
    return prop


def _type(prop, root):
    prop = _resolve(prop, root)
    if 'anyOf' in prop:
        return ' or '.join(_type(p, root) for p in prop['anyOf'])
    t = prop.get('type', '')
    if isinstance(t, list):
        return ' or '.join(t)
    if t == 'array':
        it = prop.get('items', {})
        return f"array of {it.get('type', 'value')}" if it else 'array'
    return t


def _range(prop, root):
    prop = _resolve(prop, root)
    if 'enum' in prop:
        return ', '.join(f'`{v}`' for v in prop['enum'])
    parts = []
    if 'minimum' in prop:
        parts.append(f">= {prop['minimum']}")
    if 'exclusiveMinimum' in prop:
        parts.append(f"> {prop['exclusiveMinimum']}")
    if 'maximum' in prop:
        parts.append(f"<= {prop['maximum']}")
    if 'pattern' in prop:
        parts.append(f"pattern `{prop['pattern']}`")
    it = prop.get('items', {})
    if 'exclusiveMinimum' in it:
        parts.append(f"items > {it['exclusiveMinimum']}")
    if 'minItems' in prop:
        parts.append(f"length >= {prop['minItems']}" if 'maxItems' not in prop
                     else f"length {prop['minItems']}" if prop['minItems'] == prop['maxItems']
                     else f"length {prop['minItems']}-{prop['maxItems']}")
    return ', '.join(parts)


def _cell(x):
    return str(x).replace('|', '\\|').replace('\n', ' ')


def rows(schema, root=None, prefix='', required=()):
    """``(path, type, range, default, unit, description, required)`` for every leaf field."""
    root = root or schema
    out = []
    req = set(schema.get('required', ()))
    for key, prop in schema.get('properties', {}).items():
        path = f'{prefix}{key}'
        p = _resolve(prop, root)
        if p.get('properties'):
            out += rows(p, root, path + '.')
            continue
        default = p['default'] if 'default' in p else None
        out.append((path, _type(p, root), _range(p, root),
                    ('`null`' if default is None else f'`{json.dumps(default)}`') if 'default' in p else '',
                    p.get('x-unit', ''), p.get('description', ''), key in req))
    return out


def table(schema, kind):
    lines = ['| Field | Type | Range or values | Default | Unit | Description |',
             '|---|---|---|---|---|---|']
    for path, typ, rng, default, unit, desc, req in rows(schema):
        if kind == 'output':
            default = ''
            desc = desc + (' *(always present)*' if req else '')
        elif req:
            desc = desc + ' *(required)*'
        lines.append(f'| `{path}` | {_cell(typ)} | {_cell(rng)} | {_cell(default)} | {_cell(unit)} | {_cell(desc)} |')
    return '\n'.join(lines)


def render():
    inp = json.loads((SCHEMA_DIR / 'etc_input.json').read_text())
    out = json.loads((SCHEMA_DIR / 'etc_output.json').read_text())
    n_in, n_out = len(rows(inp)), len(rows(out))
    return '\n'.join([
        '<!-- Generated by scripts/gen_field_reference.py from keck_etcs/schema/*.json at build time; do not edit. -->',
        '',
        f'## Inputs ({n_in} fields)',
        '',
        _cell(inp.get('description', '')),
        '',
        table(inp, 'input'),
        '',
        f'## Outputs ({n_out} fields)',
        '',
        _cell(out.get('description', '')),
        '',
        table(out, 'output'),
        '',
    ])


def write(out=DEFAULT_OUT):
    """Write the tables (only when the content changed, so Sphinx does not rebuild needlessly)."""
    out = Path(out)
    out.parent.mkdir(parents=True, exist_ok=True)
    text = render()
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    return out


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument('--out', default=str(DEFAULT_OUT))
    a = p.parse_args()
    print(f'wrote {write(a.out)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
